### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by jbenninghoff** [ukhan/add-to-ms-todo#10]
Not being familiar with porting Chrome extensions to Firefox, is it possible to easily port this extension to Firefox?
Excellent extension on Chrome.

**Comment by ukhan** [comment]
On review now.

**Comment by ukhan** [comment]
Published: https://addons.mozilla.org/firefox/addon/add-to-microsoft-to-do/
If you notice any problems with the extension, please let me know.
