### ISSUE TITLE
Adds in default order; not as per settings

### ISSUE THREAD

**Issue by nupur-kinger** [ukhan/add-to-ms-todo#11]
Pavel,

Thank you for sharing such an amazing extension. I absolutely love this and use this all the time.

I found a small bug which I am sharing below.
A new task is always added on top of the list (which is the default setting). It should check the setting and follow the order accordingly.

Thanks,

PS: Let me know if I can help somehow.

**Comment by ukhan** [comment]
@nupur-kinger, I’m glad to hear it.

But the [Outlook Task REST API](https://docs.microsoft.com/uk-ua/previous-versions/office/office-365-api/api/version-2.0/task-rest-operations#create-tasks) does not allow this. 
However, you can always change the sorting when tasks are displayed in an application.

**Comment by nupur-kinger** [comment]
You are right. Its not there.
Display order and the actual order (order in which tasks are saved in BE) are different. Unfortunately, I often have custom ordering in my lists and like to add new tasks to the bottom by default.

**Comment by ukhan** [comment]
Then maybe the problem is not even adding but in the inability to select sorting on multiple fields. By adding a descending order of creation date, you could get the behavior you need.
