### ISSUE TITLE
Task list doesn't respect Microsoft Todo Ordering

### ISSUE THREAD

**Issue by ShravanSunder** [ukhan/add-to-ms-todo#12]
Hi the task list seems to be random.  It doesn't respect microsoft todo ordering.  I think it also takes into account the emoji  now allowed in the list.

**Comment by ukhan** [comment]
Unfortunately, the [Outlook Task REST API](https://docs.microsoft.com/uk-ua/previous-versions/office/office-365-api/api/version-2.0/task-rest-operations#get-task-folders) (the only one available when the extension created) does not allow you to get lists in the correct order.
