### ISSUE TITLE
Issue with work account

### ISSUE THREAD

**Issue by aver123** [ukhan/add-to-ms-todo#15]
Hi. I enjoy MStoDO a lot and I think that this addson is great, but I cannot make it work with my work account. It keeps asking for an approval. Can you fix it?
Thanks

 
![MStoDO](https://user-images.githubusercontent.com/47633334/110957353-87298b80-8319-11eb-9848-d597f910fc32.png)

**Comment by ukhan** [comment]
This is about domain administrator approval of upmc.edu
