### ISSUE TITLE
problem if you have multiple accounts

### ISSUE THREAD

**Issue by StevenLi-DS** [ukhan/add-to-ms-todo#18]
I have two Microsoft accounts. I use my personal account in the extension.  Sometime need to log in my work account for Outlook. However, after I do that, the extension will transfer me to the authorization page for my work account when I try to add something to my todo. I must log out and relog in my personal account in the extension to solve the issue. Is this a known issue?

**Comment by StevenLi-DS** [comment]
Thanks for the info. If I temporarily disable the extension while logging into my work account. Is this gotta help?

**Comment by StevenLi-DS** [comment]
@ukhan  I just realized that the issue could occur without logging my work account at all. It seems like every day or every another day, I will be redirected to the authorization page when trying to save something. It always leads me to the authorization page associated with my work account and I have to go to the extension setting to log out and relog in my personal account every time.

Is there any way to avoid this?

**Comment by ukhan** [comment]
@StevenLi-DS Try the following:
- Log out of all Microsoft accounts.
- Close and reopen the browser.
- Open [Microsoft ToDo](https://to-do.live.com/tasks/) and log in to your personal account (check not to log out).

**Comment by StevenLi-DS** [comment]
@ukhan Thanks buddy. This issue has occurred a few times and I just did what you suggested. I will let you know if it still happens.

**Comment by StevenLi-DS** [comment]
@ukhan Hi buddy I can now confirm that this keep happening. I even tried to reinstall the extension. It feels like this is a timeout or something so that I have to relogin every day.

**Comment by ukhan** [comment]
@StevenLi-DS If an extension is not used for longer than 24 hours, the extension has to get a new token. To get a token, the extension opens a new tab with a login form. The reason for this is described [here](https://github.com/MicrosoftDocs/azure-docs/issues/62164).

But usually, the tab opens and automatically closes in the background.

When you logged into your account, did you check the "do not log out"?

**Comment by StevenLi-DS** [comment]
It always directs me to my work account:
![Snipaste_284](https://user-images.githubusercontent.com/33796896/119355137-e9383280-bc72-11eb-81c1-9ed8c3a66e39.png)

I need to log out and relogin in the setting, but I didn't see any "do not log out". Am I missing something?
![Snipaste_783](https://user-images.githubusercontent.com/33796896/119355092-d887bc80-bc72-11eb-9214-a77f424004ab.png)

**Comment by ukhan** [comment]
By "Log out of all Microsoft accounts" I mean that the browser should not even remember the existence of a work account after that.

![2021-05-24_16-42-24](https://user-images.githubusercontent.com/1316705/119356827-8749ee00-bcaf-11eb-807a-c819af16516b.png)

**Comment by StevenLi-DS** [comment]
> By "Log out of all Microsoft accounts" I mean that the browser should not even remember the existence of a work account after that.

I certainly don't know why the extension remembers it. I just relogin to see what gotta happen.

**Comment by ukhan** [comment]
> I certainly don't know why the extension remembers it. 

It's not the extension that remembers, it's the browser.

Because of the mentioned issue, the extension cannot work through the native launchWebAuthFlow.

**Comment by StevenLi-DS** [comment]
Any suggestion to let my browser (Chrome) to unrememeber it?

**Comment by ukhan** [comment]
As an option, in this way:

![2021-05-24_18-46-01](https://user-images.githubusercontent.com/1316705/119373146-c7fe3300-bcc0-11eb-9b3d-b2074dda9603.png)

**Comment by StevenLi-DS** [comment]
@ukhan Thanks buddy. I tried and will report what happened.

**Comment by StevenLi-DS** [comment]
@ukhan Hi man. I'm sorry to inform you that this  keep happening, and I have to log in my account every time.

**Comment by ukhan** [comment]
And the browser keeps remembering the work account?

**Comment by StevenLi-DS** [comment]
@ukhan No. After I cleared browsing data. It no longer remembered, but I still have to log in my personal account every day even though I told Microsoft to keep me sign in.

**Comment by ukhan** [comment]
There is a suspicion that your browser, for some reason, works incorrectly.

**Comment by mirko77** [comment]
I have the same issue. Using the latest Chrome and I have multiple Microsoft Accounts. There is nothing to do. I am asked to log in each day and it takes ages, maybe due to 2FA.
I just gave up, not using the extension anymore.

**Comment by ukhan** [comment]
@mirko77 If you try to open the web version of the ToDo, will you also be asked to reenter the 2FA?
