### ISSUE TITLE
Fail to get authorized

### ISSUE THREAD

**Issue by yoghurtdewdew** [ukhan/add-to-ms-todo#19]
When I try to "get started", it seems like can't get authorized.

After trying to log in, it shows:

我们无法完成你的请求
invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.

**Comment by ukhan** [comment]
Are you talking about the extension installed from Chrome Web Store or its fork?

**Comment by yoghurtdewdew** [comment]
I could not open the Chrome Web Store in my country, and I got the extension from this website: https://www.extfans.com/productivity/loblkkbfciiklgoblkigehhghfjfjede/

More details: version 0.19.8, with the Chrome Web Store link: chrome://extensions/?id=ngelobgkandnkfdmijkjncnhidnjkfmm

**Comment by yoghurtdewdew** [comment]
I have tried several times these days, but still can't get authorized

**Comment by ukhan** [comment]
Unfortunately, authorization will work only for extension with the original ID (`loblkkbfciiklgoblkigehhghfjfjede`).

Other IDs (like `ngelobgkandnkfdmijkjncnhidnjkfmm`) will require you to register a separate application at [portal.azure.com](https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade).

**Comment by yoghurtdewdew** [comment]
Thanks! I made it just now!
I finally found where I was wrong: I should directly drag the crx file to the browser, instead of zipping and loading the unzipped file in developer mode, which changed its original ID, unexpectedly.
