### ISSUE TITLE
Limited Drop-down List

### ISSUE THREAD

**Issue by netmizor** [ukhan/add-to-ms-todo#20]
When adding a task, the drop-down to select the desired list to send it to stops at the "L's" preventing the rest of the lists from showing...

<img width="422" alt="Screen Shot 2021-09-01 at 3 18 03 PM" src="https://user-images.githubusercontent.com/2362924/131730912-8bdd1e33-515b-4768-bcae-5bc7b7fe7b6e.png">

BTW, it is a very useful extension!

**Comment by ukhan** [comment]
Usually, all lists are displayed, even if there are many, but sometimes the API does not return all.

To understand what's going on, let's look at the debugging information:
- Options → Save debug info → ON
- Get the lists (open the extension window)
- View Debug Info (in the context menu of the extension)
