### ISSUE TITLE
Feature: Make the list dropdown searchable

### ISSUE THREAD

**Issue by ShravanSunder** [ukhan/add-to-ms-todo#21]
# Problem:
finding the appropriate list is cumbersome if your list is large, or has emojis.
- ![image](https://user-images.githubusercontent.com/5294949/135131955-3ea2cbea-793c-4563-b820-3ce0e0020856.png)
- 
# Proposal
## Make the list dropdown into a searchable 
- a searchable dropdown instead of a plain dropdown would help

## Settings
- a exclusion list in settings
- This list will filter the dropdown results such that they wouldn't be shown

**Comment by ukhan** [comment]
Try to start typing the name of the desired list when the dropdown is open.
The interface is not particularly neat, but the filtering works there.

**Comment by ShravanSunder** [comment]
> Try to start typing the name of the desired list when the dropdown is open. The interface is not particularly neat, but the filtering works there.

oh thanks! the filtering works! 👍🏾 

do you think the exclusion list is a good feature?

**Comment by ukhan** [comment]
> do you think the exclusion list is a good feature?

At first glance, it looks redundant, especially in the presence of filtration.
