### ISSUE TITLE
Authentification not longer working

### ISSUE THREAD

**Issue by tho-maj** [ukhan/add-to-ms-todo#27]
I get this error message:

Die Website ist nicht erreichbar
Prüfen Sie, ob "loblkkbfciiklgoblkigehhghfjfjede.chromiumapp.org" einen Tippfehler enthält.
Wenn die URL keinen Tippfehler enthält, [können Sie die Windows-Netzwerkdiagnose durchführen](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by ukhan** [comment]
Workaround: refresh page after this.

**Comment by tho-maj** [comment]
It doesn't work. Is this the correct URL: https://loblkkbfciiklgoblkigehhghfjfjede.chromiumapp.org/?code=M.R3_BL2.0871e2bd-1336-1007-1161-a5da015d8556&state=10BxsZ8NPyTC

?

**Comment by ukhan** [comment]
URL is correct. The extension should intercept this URL and take the `code` from there. Why this didn't happen, I don't know yet. 

We will assume that this happened because of the specific location of the stars :)
