### ISSUE TITLE
Today's task badges

### ISSUE THREAD

**Issue by jedielson** [ukhan/add-to-ms-todo#3]
Hi. 

First, This is an amazing extension! Congrats.

Is there any chance of we have a badge showing the number of today's tasks?

Also, is there any roadmap ou someting?

And, how can we contribute?

**Comment by ukhan** [comment]
Unfortunately, the current [Outlook Task REST API](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/task-rest-operations) does not allow this and much more ([eg](https://get.momentumdash.help/hc/en-us/articles/360047035674)).

Microsoft Graph To Do API has been [announced](https://developer.microsoft.com/en-us/graph/blogs/introducing-the-new-microsoft-graph-to-do-api/) but is not yet available even in beta.
