### ISSUE TITLE
Add to My Day

### ISSUE THREAD

**Issue by wmertens** [ukhan/add-to-ms-todo#30]
It would be great if the popup would allow adding the new task to My Day as well.

**Comment by ukhan** [comment]
Unfortunately, Microsoft To Do API doesn't allow it. [Task props](https://docs.microsoft.com/en-us/graph/api/resources/todotask?view=graph-rest-1.0#properties).

You can read more about API limitations, for example, [here](https://get.momentumdash.help/hc/en-us/articles/360047035674).
