### ISSUE TITLE
loblkkbfciiklgoblkigehhghfjfjede.chromiumapp.org cannot be resolved

### ISSUE THREAD

**Issue by Philantrop** [ukhan/add-to-ms-todo#32]
loblkkbfciiklgoblkigehhghfjfjede.chromiumapp.org cannot be resolved for a few days now. No reload, etc. will help; it's simply DNS:

```
dig @8.8.8.8  loblkkbfciiklgoblkigehhghfjfjede.chromiumapp.org 

; <<>> DiG 9.16.30-RH <<>> @8.8.8.8 loblkkbfciiklgoblkigehhghfjfjede.chromiumapp.org
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 48326
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;loblkkbfciiklgoblkigehhghfjfjede.chromiumapp.org. IN A
```
Any workaround?

**Comment by ukhan** [comment]
Try restarting the browser (including the background process) or the computer and use the extension again.

The error is not in the address or the network problem but that the extension didn't see this redirect but should have seen it.

**Comment by Philantrop** [comment]
Thank you, restarting the browser did indeed fix it - this time. It's occurring more and more often, though. Is there any way to properly debug this?

**Comment by ukhan** [comment]
I don't have any idea how to debug this. We have the case when an observer (debugger) will influence the process. The extension during debugging is constantly active, and there will be no problems intercepting the redirect.

This authentication process was a crutch to work around the identity.launchWebAuthFlow and 24-hour lifetime refresh token incompatibility issue. Details: 
- https://github.com/MicrosoftDocs/azure-docs/issues/62164
- https://bugs.chromium.org/p/chromium/issues/detail?id=907920

Now with manifest v3, we could do without this crutch. Maybe I'll do it later.
