### ISSUE TITLE
Extension repeatedly tries and fails to log back in (possibly related to / after Windows update)

### ISSUE THREAD

**Issue by blinkertoon** [ukhan/add-to-ms-todo#36]
FYI it may / not be related to the fact that I often have to remove and re-add my work account on this laptop after a Windows update.

**Comment by hammadmajid** [comment]
Faced the same issue. In my case the extension tries to log back in every time I restarted my browser. 

**Extension version:** 0.20.0
**Browser:** Microsoft Edge
**Version:** 108.0.1462.46 (Official build) (64-bit)
