### ISSUE TITLE
Inserting tasks on the wrong side of lists

### ISSUE THREAD

**Issue by mcandre** [ukhan/add-to-ms-todo#38]
Hi,

I prefer to place new tasks at the top of my lists. However, this extension appears to always place tasks at the bottom of lists.

Can we please receive a menu option to insert new tasks at the Top or Bottom, according to the user's preference?

**Comment by ukhan** [comment]
[Microsoft To Do API](https://learn.microsoft.com/en-us/graph/api/todotasklist-post-tasks?view=graph-rest-1.0) does not provide an option to specify the position of a task in the list when adding it.
