### ISSUE TITLE
Constant logout

### ISSUE THREAD

**Issue by cedomirovic** [ukhan/add-to-ms-todo#41]
The extension is constantly logging me out after I close the browser. Any idea how to prevent it? Tnx!

**Comment by ukhan** [comment]
How about this?
![2023-08-29_17-17-29](https://github.com/ukhan/add-to-ms-todo/assets/1316705/53cf2d1b-d8c7-4a67-8943-fbda54384910)

**Comment by cedomirovic** [comment]
I already tried that. After every browser restart, I need to login in again.
