### ISSUE TITLE
List Tasks, allow drop down's width be wider so long task list names are 100% visible

### ISSUE THREAD

**Issue by samkatakouzinos** [ukhan/add-to-ms-todo#42]
Q: Would it be possible to allow the drop down list to overflow the dialog to allow the full width of my task list names?  

I have long task list names and they cannot be fully shown.

<details open>  
  <summary>Screenshot (Long Task List Names)</summary>  

  ![DoJynRBiM8-2](https://github.com/ukhan/add-to-ms-todo/assets/1305871/e9495539-9a1d-444a-8b97-d4a357ec06f5)  
</details>  

This makes shorter task list names not 100% visible and are clipped

<details open>  
  <summary>Screenshot (Clipped Task List Names)</summary>  

  ![rvXfbgnyrl](https://github.com/ukhan/add-to-ms-todo/assets/1305871/46235627-b082-442a-a1c9-91a7a4ba3ef1)  
</details>

**Comment by ukhan** [comment]
Fixed in version 0.21.0 (currently in review).

**Comment by samkatakouzinos** [comment]
I appreciate this update.
Having the task list stay left aligned is far better even though it's not "wider so long task list names are 100% visible" as requested.
With this I can get more work done now. 
Thank you.
