### ISSUE TITLE
Adding the option to not pre-populate the fields

### ISSUE THREAD

**Issue by ali92hm** [ukhan/add-to-ms-todo#8]
Hey,

First of all thank you for making this extension. It's a shame there is no official extension for Todo.

While I think the main use case that prompted you to create this extension is to add web urls to a todo list, I've been using it to add anything that pops to my mind without switching from my browser to the ToDo app. It's a little annoying to delete the pre populated text from the extension and write my own. 

I was wondering if you'd be fine with me making a pull request and adding an option to not pre-populate the fields when the extension is clicked.

**Comment by ukhan** [comment]
[I made it](https://github.com/ukhan/add-to-ms-todo/commit/adbd736c65db65e8f28f8e67eeaa33ede1535c7a) a little trickier – in addition to the settings itself, I also added a button to switch the state of the form right in the extension's pop-up window.

**Comment by ali92hm** [comment]
Damn, I tried it. Thank you so much!
