### ISSUE TITLE
A logo for "Microsoft Edge Add-ons"

### ISSUE THREAD

**Issue by moleng09** [ukhan/add-to-ms-todo#9]
![Add to MS  ToDo](https://user-images.githubusercontent.com/54031747/95745238-47596c00-0cc7-11eb-8354-ee9800707811.png)

**Comment by ukhan** [comment]
Thanks. Publishing in progress.

**Comment by ukhan** [comment]
Done: https://microsoftedge.microsoft.com/addons/detail/add-to-microsoft-to-do/gmlpcoahadjmjhgipekkeickjllmllho
Thanks again.
